// Generated by gencpp from file cup_detect/mission_cameraResponse.msg
// DO NOT EDIT!


#ifndef CUP_DETECT_MESSAGE_MISSION_CAMERARESPONSE_H
#define CUP_DETECT_MESSAGE_MISSION_CAMERARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cup_detect
{
template <class ContainerAllocator>
struct mission_cameraResponse_
{
  typedef mission_cameraResponse_<ContainerAllocator> Type;

  mission_cameraResponse_()
    : coordinate_camera()
    , cup_color_camera(0)  {
    }
  mission_cameraResponse_(const ContainerAllocator& _alloc)
    : coordinate_camera(_alloc)
    , cup_color_camera(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _coordinate_camera_type;
  _coordinate_camera_type coordinate_camera;

   typedef int32_t _cup_color_camera_type;
  _cup_color_camera_type cup_color_camera;





  typedef boost::shared_ptr< ::cup_detect::mission_cameraResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cup_detect::mission_cameraResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mission_cameraResponse_

typedef ::cup_detect::mission_cameraResponse_<std::allocator<void> > mission_cameraResponse;

typedef boost::shared_ptr< ::cup_detect::mission_cameraResponse > mission_cameraResponsePtr;
typedef boost::shared_ptr< ::cup_detect::mission_cameraResponse const> mission_cameraResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cup_detect::mission_cameraResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cup_detect::mission_cameraResponse_<ContainerAllocator1> & lhs, const ::cup_detect::mission_cameraResponse_<ContainerAllocator2> & rhs)
{
  return lhs.coordinate_camera == rhs.coordinate_camera &&
    lhs.cup_color_camera == rhs.cup_color_camera;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cup_detect::mission_cameraResponse_<ContainerAllocator1> & lhs, const ::cup_detect::mission_cameraResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cup_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cup_detect::mission_cameraResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cup_detect::mission_cameraResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cup_detect::mission_cameraResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b944d6e2d2bded5588d47fc18e802eb8";
  }

  static const char* value(const ::cup_detect::mission_cameraResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb944d6e2d2bded55ULL;
  static const uint64_t static_value2 = 0x88d47fc18e802eb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cup_detect/mission_cameraResponse";
  }

  static const char* value(const ::cup_detect::mission_cameraResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] coordinate_camera\n"
"int32 cup_color_camera\n"
;
  }

  static const char* value(const ::cup_detect::mission_cameraResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coordinate_camera);
      stream.next(m.cup_color_camera);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mission_cameraResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cup_detect::mission_cameraResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cup_detect::mission_cameraResponse_<ContainerAllocator>& v)
  {
    s << indent << "coordinate_camera[]" << std::endl;
    for (size_t i = 0; i < v.coordinate_camera.size(); ++i)
    {
      s << indent << "  coordinate_camera[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.coordinate_camera[i]);
    }
    s << indent << "cup_color_camera: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cup_color_camera);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUP_DETECT_MESSAGE_MISSION_CAMERARESPONSE_H
