// Generated by gencpp from file cup_detect/transSrvRequest.msg
// DO NOT EDIT!


#ifndef CUP_DETECT_MESSAGE_TRANSSRVREQUEST_H
#define CUP_DETECT_MESSAGE_TRANSSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cup_detect
{
template <class ContainerAllocator>
struct transSrvRequest_
{
  typedef transSrvRequest_<ContainerAllocator> Type;

  transSrvRequest_()
    : camera_x(0)
    , camera_y(0)  {
    }
  transSrvRequest_(const ContainerAllocator& _alloc)
    : camera_x(0)
    , camera_y(0)  {
  (void)_alloc;
    }



   typedef int64_t _camera_x_type;
  _camera_x_type camera_x;

   typedef int64_t _camera_y_type;
  _camera_y_type camera_y;





  typedef boost::shared_ptr< ::cup_detect::transSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cup_detect::transSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct transSrvRequest_

typedef ::cup_detect::transSrvRequest_<std::allocator<void> > transSrvRequest;

typedef boost::shared_ptr< ::cup_detect::transSrvRequest > transSrvRequestPtr;
typedef boost::shared_ptr< ::cup_detect::transSrvRequest const> transSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cup_detect::transSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cup_detect::transSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cup_detect::transSrvRequest_<ContainerAllocator1> & lhs, const ::cup_detect::transSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.camera_x == rhs.camera_x &&
    lhs.camera_y == rhs.camera_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cup_detect::transSrvRequest_<ContainerAllocator1> & lhs, const ::cup_detect::transSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cup_detect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cup_detect::transSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cup_detect::transSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cup_detect::transSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cup_detect::transSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cup_detect::transSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cup_detect::transSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cup_detect::transSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90edab8f77b22eea4744a01007336d84";
  }

  static const char* value(const ::cup_detect::transSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90edab8f77b22eeaULL;
  static const uint64_t static_value2 = 0x4744a01007336d84ULL;
};

template<class ContainerAllocator>
struct DataType< ::cup_detect::transSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cup_detect/transSrvRequest";
  }

  static const char* value(const ::cup_detect::transSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cup_detect::transSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 camera_x\n"
"int64 camera_y\n"
;
  }

  static const char* value(const ::cup_detect::transSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cup_detect::transSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_x);
      stream.next(m.camera_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct transSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cup_detect::transSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cup_detect::transSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "camera_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.camera_x);
    s << indent << "camera_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.camera_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUP_DETECT_MESSAGE_TRANSSRVREQUEST_H
